# The main workflow is intended to run unit tests on each commit to or pull request made to develop

name: Unit Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ feat/v2 ]
  pull_request:
    branches: [ feat/v2 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: feat/v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # Latest 3.1 patch version
      - run: dotnet build .\ExternalApp\Genesis\Genesis.sln
      - run: dotnet test .\ExternalApp\Genesis\Genesis.sln --no-build --verbosity normal
      - uses: actions/cache@v1.1.0
        with:
          path: Unity/Library
          key: Library-Genesis-Windows
          restore-keys: |
            Library-Genesis-
            Library-
            
      # Runs a single command using the runners shell
      - uses: webbertakken/unity-test-runner@v1.4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: Unity
          unityVersion: 2019.4.8f1
                      
      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: artifacts
